"""
Auto-generated by Code-Writer Agent
Timestamp : 2026-07-31 08:55:37
"""

def find_vowels(input_string: str) -> list[str]:
    """
    Find all the vowels in the input string.

    Args:
        input_string (str): The input string to find vowels in.

    Returns:
        list[str]: A list of vowels found in the input string.
    """
    if not isinstance(input_string, str):
        raise ValueError("Input must be a string")
    vowels = 'aeiouAEIOU'
    return [char for char in input_string if char in vowels]

def main():
    """
    Test the find_vowels function with some examples.
    """
    print(find_vowels("Hello World"))  # Expected output: ['e', 'o']
    print(find_vowels(""))  # Expected output: []
    try:
        print(find_vowels(123))  # Expected output: ValueError
    except ValueError as e:
        print(e)
    try:
        print(find_vowels(None))  # Expected output: ValueError
    except ValueError as e:
        print(e)

if __name__ == '__main__':
    main()