"""
Auto-generated by Code-Writer Agent
Timestamp : 2026-07-31 08:10:32
"""

import statistics
from typing import List, Union

def calculate_statistics(numbers: List[Union[int, float]]) -> dict:
    """
    Calculate the mean, median, and mode of a list of numbers.

    Args:
        numbers: A list of numbers.

    Returns:
        A dictionary with the mean, median, and mode.

    Raises:
        ValueError: If the input list is empty.
    """
    if not numbers:
        raise ValueError("Input list is empty")

    try:
        mean = statistics.mean(numbers)
        median = statistics.median(numbers)
        mode = statistics.multimode(numbers)
    except statistics.StatisticsError:
        raise ValueError("Input list contains duplicate values")

    if len(mode) == 1:
        mode = mode[0]
    else:
        mode = mode

    return {"mean": mean, "median": median, "mode": mode}


def main():
    numbers = [1, 2, 2, 3, 4, 4, 4]
    try:
        stats = calculate_statistics(numbers)
        print("Mean:", stats["mean"])
        print("Median:", stats["median"])
        print("Mode:", stats["mode"])
    except ValueError as e:
        print("Error:", e)

    numbers = [1, 2, 3, 4, 5]
    try:
        stats = calculate_statistics(numbers)
        print("Mean:", stats["mean"])
        print("Median:", stats["median"])
        print("Mode:", stats["mode"])
    except ValueError as e:
        print("Error:", e)


if __name__ == '__main__':
    main()